blank_issues_enabled: false
contact_links:
  - name: B2S Server community forum on vpuniverse
    url: https://vpuniverse.com/forums/forum/88-b2s-new-releases
    about: Before adding an issue, please discuss possible solutions here.
