name: b2s-backglass
on:
  push:

defaults:
  run:
    shell: bash

jobs:
  build-server:
    name: Build B2SBackglassServer
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - id: version
        name: Update AssemblyInformationalVersion
        run: |
          SHA7="${GITHUB_SHA::7}"
          ASSEMBLY_INFO="b2sbackglassserverexe/b2sbackglassserverexe/My Project/AssemblyInfo.vb"
          VERSION=$(grep -Eo "AssemblyVersion\(.*\)" "${ASSEMBLY_INFO}" | grep -Eo "[0-9\.]+" | tail -1)
          TAG="${VERSION}-${SHA7}"
          perl -i -pe"s/AssemblyInformationalVersion\(\".*\"\)/AssemblyInformationalVersion\(\"${TAG}\"\)/g" "${ASSEMBLY_INFO}"
          ASSEMBLY_INFO="b2sbackglassserverregisterapp/b2sbackglassserverregisterapp/My Project/AssemblyInfo.vb"
          VERSION=$(grep -Eo "AssemblyVersion\(.*\)" "${ASSEMBLY_INFO}" | grep -Eo "[0-9\.]+" | tail -1)
          TAG="${VERSION}-${SHA7}"
          perl -i -pe"s/AssemblyInformationalVersion\(\".*\"\)/AssemblyInformationalVersion\(\"${TAG}\"\)/g" "${ASSEMBLY_INFO}"
          ASSEMBLY_INFO="b2sbackglassserver/b2sbackglassserver/My Project/AssemblyInfo.vb"
          VERSION=$(grep -Eo "AssemblyVersion\(.*\)" "${ASSEMBLY_INFO}" | grep -Eo "[0-9\.]+" | tail -1)
          TAG="${VERSION}-${SHA7}"
          perl -i -pe"s/AssemblyInformationalVersion\(\".*\"\)/AssemblyInformationalVersion\(\"${TAG}\"\)/g" "${ASSEMBLY_INFO}"
          echo "::set-output name=tag::${TAG}"
      - uses: microsoft/setup-msbuild@v1.1
      - name: Build
        run: |
          msbuild b2sbackglassserverexe/B2SBackglassServerEXE.sln /t:Rebuild /p:Configuration=Release
          msbuild b2sbackglassserverregisterapp/B2SBackglassServerRegisterApp.sln /t:Rebuild /p:Configuration=Release
          msbuild b2sbackglassserver/B2SBackglassServer.sln /t:Rebuild /p:Configuration=Release
        shell: cmd
      - name: Bundle
        run: |
          mkdir tmp  
          cp b2sbackglassserverexe/b2sbackglassserverexe/bin/Release/B2SBackglassServerEXE.exe tmp
          cp b2sbackglassserverregisterapp/b2sbackglassserverregisterapp/bin/x64/Release/B2SBackglassServerRegisterApp.exe tmp
          cp b2sbackglassserver/b2sbackglassserver/bin/Release/B2SServerPluginInterface.dll tmp
          cp b2sbackglassserver/b2sbackglassserver/bin/Release/B2SBackglassServer.dll tmp
          cp Changelog.txt tmp
          cp license.txt tmp
          cp README.md tmp
          cp ScreenRes.txt tmp
      - uses: actions/upload-artifact@v3
        with:
         name: B2SBackglassServer-${{ steps.version.outputs.tag }}
         path: tmp

  build-designer:
    name: Build B2SBackglassDesigner
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - id: version
        name: Update AssemblyInformationalVersion
        run: |
          SHA7="${GITHUB_SHA::7}"
          ASSEMBLY_INFO="b2sbackglassdesigner/b2sbackglassdesigner/My Project/AssemblyInfo.vb"
          VERSION=$(grep -Eo "AssemblyVersion\(.*\)" "${ASSEMBLY_INFO}" | grep -Eo "[0-9\.]+" | tail -1)
          TAG="${VERSION}-${SHA7}"
          perl -i -pe"s/AssemblyInformationalVersion\(\".*\"\)/AssemblyInformationalVersion\(\"${TAG}\"\)/g" "${ASSEMBLY_INFO}"
          echo "::set-output name=tag::${TAG}"
      - uses: microsoft/setup-msbuild@v1.1
      - name: Build
        run: |
          msbuild b2sbackglassdesigner/B2SBackglassDesigner.sln /t:Rebuild /p:Configuration=Release
        shell: cmd
      - name: Help
        run: |
          choco install html-help-workshop
          "/c/Program Files (x86)/HTML Help Workshop/hhc.exe" "b2sbackglassdesigner/b2sbackglassdesigner/htmlhelp/B2SBackglassDesigner.hhp" || true
      - name: Bundle
        run: |
          mkdir tmp  
          cp b2sbackglassdesigner/b2sbackglassdesigner/bin/x64/Release/B2SBackglassDesigner.exe tmp
          cp b2sbackglassdesigner/b2sbackglassdesigner/htmlhelp/B2SBackglassDesigner.chm tmp
          cp B2SVPinMAMEStarter/B2SVPinMAMEStarter.exe tmp
          cp license.txt tmp
      - uses: actions/upload-artifact@v3
        with:
         name: B2SBackglassDesigner-${{ steps.version.outputs.tag }}
         path: tmp

  build-screenresidentifer:
    name: Build B2S_ScreenResIdentifier
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - id: version
        name: Update AssemblyInformationalVersion
        run: |
          SHA7="${GITHUB_SHA::7}"
          ASSEMBLY_INFO="b2s_screenresidentifier/b2s_screenresidentifier/My Project/AssemblyInfo.vb"
          VERSION=$(grep -Eo "AssemblyVersion\(.*\)" "${ASSEMBLY_INFO}" | grep -Eo "[0-9\.]+" | tail -1)
          TAG="${VERSION}-${SHA7}"
          perl -i -pe"s/AssemblyInformationalVersion\(\".*\"\)/AssemblyInformationalVersion\(\"${TAG}\"\)/g" "${ASSEMBLY_INFO}"
          echo "::set-output name=tag::${TAG}"
      - uses: microsoft/setup-msbuild@v1.1
      - name: Build
        run: |
          msbuild b2s_screenresidentifier/B2S_ScreenResIdentifier.sln /t:Rebuild /p:Configuration=Release
        shell: cmd
      - name: Bundle
        run: |
          mkdir tmp
          cp b2s_screenresidentifier/b2s_screenresidentifier/bin/x64/Release/B2S_ScreenResIdentifier.exe tmp
          cp license.txt tmp
      - uses: actions/upload-artifact@v3
        with:
         name: B2S_ScreenResIdentifier-${{ steps.version.outputs.tag }}
         path: tmp

  build-betterled:
    name: Build BetterLed
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - id: version
        name: Update AssemblyInformationalVersion
        run: |
          SHA7="${GITHUB_SHA::7}"
          ASSEMBLY_INFO="leds/dream7segments/My Project/AssemblyInfo.vb"
          VERSION=$(grep -Eo "AssemblyVersion\(.*\)" "${ASSEMBLY_INFO}" | grep -Eo "[0-9\.]+" | tail -1)
          TAG="${VERSION}-${SHA7}"
          perl -i -pe"s/AssemblyInformationalVersion\(\".*\"\)/AssemblyInformationalVersion\(\"${TAG}\"\)/g" "${ASSEMBLY_INFO}"
          ASSEMBLY_INFO="leds/BetterLed/My Project/AssemblyInfo.vb"
          VERSION=$(grep -Eo "AssemblyVersion\(.*\)" "${ASSEMBLY_INFO}" | grep -Eo "[0-9\.]+" | tail -1)
          TAG="${VERSION}-${SHA7}"
          perl -i -pe"s/AssemblyInformationalVersion\(\".*\"\)/AssemblyInformationalVersion\(\"${TAG}\"\)/g" "${ASSEMBLY_INFO}"
          echo "::set-output name=tag::${TAG}"
      - uses: microsoft/setup-msbuild@v1.1
      - name: Build
        run: |
          msbuild leds/BetterLed/BetterLed.sln /t:Rebuild /p:Configuration=Release
        shell: cmd
      - name: Bundle
        run: |
          mkdir tmp
          cp leds/BetterLed/bin/Release/BetterLed.exe tmp
          cp leds/BetterLed/bin/Release/Dream7Display.dll tmp
          cp license.txt tmp
      - uses: actions/upload-artifact@v3
        with:
         name: BetterLed-${{ steps.version.outputs.tag }}
         path: tmp
